create table
  public.wars (
    id integer generated by default as identity,
    planet_1 text not null default ''::text,
    planet_2 text not null default ''::text,
    constraint wars_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.planets (
    planet text not null,
    war_id integer not null,
    constraint planets_pkey primary key (planet),
    constraint planets_war_id_fkey foreign key (war_id) references wars (id)
  ) tablespace pg_default;

create table
  public.citizens (
    id integer generated by default as identity,
    name text not null default ''::text,
    role text not null default ''::text,
    bid_id integer null,
    strikes integer not null default 0,
    planet text not null,
    constraint civilians_pkey primary key (id),
    constraint citizens_planet_fkey foreign key (planet) references planets (planet)
  ) tablespace pg_default;

create table
  public.inventory (
    citizen_id integer not null,
    type text not null default ''::text,
    quantity integer null default 0,
    name text not null default ''::text,
    constraint inventory_pkey primary key (citizen_id)
  ) tablespace pg_default;

create table
  public.market (
    id integer generated by default as identity,
    name text not null default ''::text,
    type text not null default ''::text,
    price integer not null default 0,
    quantity integer not null default 0,
    seller_id integer null,
    timestamp timestamp without time zone null default now(),
    constraint market_pkey primary key (id),
    constraint market_seller_id_fkey foreign key (seller_id) references citizens (id)
  ) tablespace pg_default;

create table
  public.transactions (
    transaction_id bigint not null,
    buyer_id integer null,
    constraint transactions_pkey primary key (transaction_id),
    constraint transactions_buyer_id_fkey foreign key (buyer_id) references citizens (id)
  ) tablespace pg_default;

create table
  public.transaction_items (
    transaction_id integer not null,
    quantity integer not null default 0,
    listing text not null default ''::text,
    type text not null default ''::text,
    constraint transaction_items_pkey primary key (transaction_id),
    constraint transaction_items_transaction_id_fkey foreign key (transaction_id) references transactions (transaction_id)
  ) tablespace pg_default;

create table
  public.narcos (
    id bigint generated by default as identity,
    name text null,
    price integer null,
    rarity integer null,
    constraint narcos_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.substances (
    id integer generated by default as identity,
    name text null,
    price integer null,
    rarity integer null,
    planet text null,
    constraint substances_pkey primary key (id),
    constraint substances_planet_fkey foreign key (planet) references planets (planet)
  ) tablespace pg_default;

